CREATE TABLE `top_users_activty` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`ip` VARCHAR(20) NOT NULL DEFAULT '0.0.0.0' COLLATE 'utf8_general_ci',
	PRIMARY KEY (`id`)
)
COLLATE='utf32_general_ci'
ENGINE=InnoDB;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='top100';
SHOW TABLE STATUS FROM `top100`;
SHOW FUNCTION STATUS WHERE `Db`='top100';
SHOW PROCEDURE STATUS WHERE `Db`='top100';
SHOW TRIGGERS FROM `top100`;
SHOW EVENTS FROM `top100`;
SHOW CREATE TABLE `top100`.`top_users_activty`;