CREATE TABLE `top_monthly_income` (
	`month` VARCHAR(255) NULL COLLATE 'utf8_general_ci'
)
COLLATE='utf32_general_ci'
ENGINE=InnoDB;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='top100';
SHOW TABLE STATUS FROM `top100`;
SHOW FUNCTION STATUS WHERE `Db`='top100';
SHOW PROCEDURE STATUS WHERE `Db`='top100';
SHOW TRIGGERS FROM `top100`;
SHOW EVENTS FROM `top100`;
SHOW CREATE TABLE `top100`.`top_monthly_income`;
/* Entering session "localhost" */
ALTER TABLE `top_monthly_income`
	ADD COLUMN `amount` BIGINT UNSIGNED NOT NULL DEFAULT '0' AFTER `month`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='top100';
SHOW TABLE STATUS FROM `top100`;
SHOW FUNCTION STATUS WHERE `Db`='top100';
SHOW PROCEDURE STATUS WHERE `Db`='top100';
SHOW TRIGGERS FROM `top100`;
SHOW EVENTS FROM `top100`;
SHOW CREATE TABLE `top100`.`top_monthly_income`;