ALTER TABLE `top_sites`
	CHANGE COLUMN `baner_url` `banner_url` VARCHAR(500) NOT NULL DEFAULT 'top_default' COLLATE 'utf8_general_ci' AFTER `out_votes`,
	ADD COLUMN `url` VARCHAR(500) NOT NULL DEFAULT 'top_default' AFTER `banner_url`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='top100';
SHOW TABLE STATUS FROM `top100`;
SHOW FUNCTION STATUS WHERE `Db`='top100';
SHOW PROCEDURE STATUS WHERE `Db`='top100';
SHOW TRIGGERS FROM `top100`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='top100';
SHOW CREATE TABLE `top100`.`top_sites`;