CREATE TABLE `top_blacklist_url` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`url` VARCHAR(25) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf32_general_ci'
ENGINE=InnoDB
;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='top100';
SHOW TABLE STATUS FROM `top100`;
SHOW FUNCTION STATUS WHERE `Db`='top100';
SHOW PROCEDURE STATUS WHERE `Db`='top100';
SHOW TRIGGERS FROM `top100`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='top100';
SHOW CREATE TABLE `top100`.`top_blacklist_url`;
/* Entering session "localhost" */
SHOW CREATE TABLE `top100`.`top_blacklist_url`;